name: Pelican site CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: gerrowadat/gh-pages-pelican-action@0.0.2
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PELICAN_CONFIG_FILE: publishconf.py
        GH_PAGES_CNAME: log.andvari.net
